from decouple import Config, RepositoryEnv
import os

# --- CAMINHO EXPLÍCITO PARA O ARQUIVO .ENV ---
# Esta linha constrói o caminho completo para o arquivo .env, garantindo que ele sempre seja encontrado.
DOTENV_PATH = os.path.join(os.path.dirname(__file__), '.env')

# Cria uma instância de configuração que LÊ ESSE ARQUIVO ESPECÍFICO
env_config = Config(RepositoryEnv(DOTENV_PATH))

# --- CHAVES DE ACESSO E TOKENS ---
TELEGRAM_TOKEN = env_config('TELEGRAM_TOKEN')
TELEGRAM_CHAT_ID = env_config('TELEGRAM_CHAT_ID')
API_KEY_ODDS = env_config('API_KEY_ODDS')

# --- DICIONÁRIO DE RISCO E NÍVEIS DE ODDS ---
NIVEIS_DE_RISCO_ODDS = {
    "SUPER_FAVORITO": {"min": 1.30, "max": 1.49},
    "FAVORITO":       {"min": 1.50, "max": 1.80},
    "RISCO_MEDIO":    {"min": 1.81, "max": 2.50},
    "RISCO_ALTO":     {"min": 2.51, "max": 6.00},
    "RISCO_EXTREMO":  {"min": 6.01, "max": 999.0}
}

# --- PARÂMETROS GLOBAIS ---
ODD_MINIMA_GLOBAL = 1.50
DIA_DO_RELATORIO_SEMANAL = 6 
CACHE_EXPIRATION_HOURS = 6 

# --- PARÂMETROS DAS ESTRATÉGIAS ---
MIN_JOGOS_HISTORICO = 6
MIN_JOGOS_H2H = 3
BTTS_MIN_AVG_GOLS_PARTIDA = 2.8
CANTOS_NUM_JOGOS_ANALISE = 8
CANTOS_MEDIA_MINIMA_TOTAL = 10.5
SUPER_FAVORITO_MAX_ODD = 1.50 # Substituído SUPER_FAVORITO_MAX_IMPAR
FAVORITO_MAX_ODD = 1.65 # Substituído FAVORITO_MAX_IMPAR
ODD_MINIMA_FAVORITO = 1.30 # Substituído IMPAR_MINIMO_FAVORITO
MERCADO_OTIMISTA_MAX_ODD = 1.60
ODD_MINIMA_OVER_Otimista = 1.30
CONSENSO_FAVORITO_MAX_ODD = 1.50
CONSENSO_MERCADO_OVER_MAX_ODD = 1.60
CONSENSO_OVER_MIN_ODD_VALOR = 1.70
CONSENSO_EMPATE_MAX_ODD = 3.20
CONSENSO_MERCADO_UNDER_MAX_ODD = 1.80
CONSENSO_UNDER_MIN_ODD_VALOR = 1.70
LINHA_ESTICADA_OVER_2_5_MAX_ODD = 1.50
LINHA_ESTICADA_UNDER_3_5_MIN_ODD = 1.70
ZEBRA_VALOROSA_FAVORITO_MAX_ODD = 1.35
ZEBRA_VALOROSA_EMPATE_MIN_ODD = 3.50
ZEBRA_VALOROSA_EMPATE_MAX_ODD = 5.00
FAVORITO_CONSERVADOR_MAX_ODD = 1.50
FAVORITO_CONSERVADOR_OVER_1_5_MIN_ODD = 1.30
PRESSAO_MERCADO_OVER_2_5_MIN_ODD = 1.70
PRESSAO_MERCADO_OVER_2_5_MAX_ODD = 1.85
GOLEADOR_CASA_MIN_AVG_GOLS = 1.70
GOLEADOR_CASA_MIN_ODD_OVER_1_5 = 1.30
VISITANTE_FRACO_MIN_PERC_DERROTAS = 50.0
VISITANTE_FRACO_ODD_CASA_MIN = 1.40
VISITANTE_FRACO_ODD_CASA_MAX = 4.00
MANDANTE_FRACO_MIN_PERC_DERROTAS_CASA = 40.0
MANDANTE_FRACO_ODD_FORA_MIN = 1.50
MANDANTE_FRACO_ODD_FORA_MAX = 3.00
CLASSICO_GOLS_MIN_AVG = 3.0
CLASSICO_GOLS_MIN_ODD_OVER_2_5 = 1.70
FORTALEZA_DEFENSIVA_MAX_AVG_GOLS_SOFRIDOS = 0.85
FORTALEZA_DEFENSIVA_MIN_ODD_UNDER_2_5 = 1.60
GIGANTE_MIN_PERC_VITORIAS = 60.0
GIGANTE_MIN_ODD_VITORIA = 1.40
LIDER_VS_LANTERNA_ODD_MIN = 1.40
LIDER_VS_LANTERNA_POSICAO_MAX_LIDER = 3
LIDER_VS_LANTERNA_POSICAO_MIN_LANTERNA = 3
PRESSAO_MERCADO_MIN_ODD_DROP_PERCENT = 15.0
PRESSAO_MERCADO_OPENING_ODD_MIN = 1.70
PRESSAO_MERCADO_OPENING_ODD_MAX = 2.50
PRESSAO_MERCADO_CURRENT_ODD_MAX = 1.90
CANTOS_HISTORICO_MIN_AVG_PRO = 6.0
CANTOS_HISTORICO_MIN_AVG_CONTRA = 5.0
CANTOS_HISTORICO_MIN_SUM_GERAL = 11.0
PRESSAO_OFENSIVA_MIN_REMATES_PRO = 10.0
PRESSAO_OFENSIVA_MIN_REMATES_ALVO_PRO = 4.5
PRESSAO_OFENSIVA_MIN_ODD_OVER_2_5 = 1.50
CARTOES_MIN_AVG_EQUIPA = 2.2
CARTOES_MIN_AVG_JOGO_SUM = 5.0
PRESSAO_EXTREMA_MIN_REMATES_PRO = 16.0
PRESSAO_EXTREMA_MIN_REMATES_ALVO_PRO = 5.5
PRESSAO_EXTREMA_ODD_MIN = 1.40
PRESSAO_EXTREMA_ODD_MAX = 1.50
JOGO_EQUILIBRADO_MIN_ODD = 2.20
ODD_MINIMA_UNDER_Tatico = 1.60