# Nome do nosso segundo fluxo de trabalho
name: Gerar Relatório Diário de Performance

on:
  schedule:
    # Esta expressão 'cron' significa "Às 02:00 UTC", que corresponde às 23:00 da noite
    # no seu fuso horário (UTC-3), todos os dias. Perfeito para um relatório diário.
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Isso também adiciona o botão para você rodar o relatório manualmente quando quiser

jobs:
  build-report:
    # A permissão de 'read' é suficiente, pois ele só precisa ler o arquivo de histórico
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Baixar o código e os arquivos de histórico
    - name: 1. Baixar o código
      uses: actions/checkout@v4

    # Passo 2: Configurar o ambiente Python
    - name: 2. Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Passo 3: Instalar as dependências (requests)
    - name: 3. Instalar dependências
      run: |
        pip install -r requirements.txt

    # Passo 4: Executar o script que gera e envia o relatório
    - name: 4. Gerar e Enviar Relatório
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python relatorio_diario.py
