name: Enviar Relatório Semanal

on:
  schedule:
    - cron: '0 15 * * 0'
  workflow_dispatch:

jobs:
  build-and-send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas python-dateutil thefuzz

      - name: Run Python script to generate report
        # --- ALTERADO ---
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID_PESSOAL: ${{ secrets.TELEGRAM_CHAT_ID_PESSOAL }}
        run: python gerar_relatorio_semanal.py

      - name: Commit the flag file
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git pull
          git add *.flag
          git diff --quiet && git diff --staged --quiet || git commit -m "Adiciona flag do relatório semanal"
          git push
