# .github/workflows/analise_jogos.yml

name: Analise de Jogos do Falcao

on:
  schedule:
    # Roda a cada 30 min, das 11:00 às 23:59 UTC (08:00 às 20:59 BRT)
    - cron: '*/30 11-23 * * *'
    # Roda a cada 30 min, das 00:00 às 02:59 UTC (21:00 às 23:59 BRT)
    - cron: '*/30 0-2 * * *'
  
  # Permite que você rode este workflow manualmente pela aba Actions do GitHub
  workflow_dispatch:

jobs:
  rodar-analise:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Baixando o código do repositório
        uses: actions/checkout@v3

      - name: 2. Configurando o ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Ou a versão que você usa

      - name: 3. Instalando as dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Executando o Robô Falcão
        env:
          # É ESSENCIAL que você configure estes segredos no seu repositório
          API_KEY_FOOTBALL: ${{ secrets.API_KEY_FOOTBALL }}
          API_KEY_ODDS: ${{ secrets.API_KEY_ODDS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
