name: Rodar Falcão da ODDS

on:
  schedule:
    # Roda a cada 4 horas
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-falcao:
    runs-on: ubuntu-latest
    
    # Define os segredos como variáveis de ambiente para todo o job
    env:
      API_KEY_ODDS: ${{ secrets.API_KEY }} 
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
    - name: 1. Baixar o código
      uses: actions/checkout@v4

    - name: 2. Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 3. Instalar dependências
      run: pip install -r requirements.txt
      
    # ETAPA DE VERIFICAÇÃO ADICIONADA
    - name: 4. Verificar se os Segredos foram Carregados
      run: |
        echo "API_KEY_ODDS_DEFINIDO: ${{ env.API_KEY_ODDS != '' }}"
        echo "TELEGRAM_TOKEN_DEFINIDO: ${{ env.TELEGRAM_TOKEN != '' }}"
        echo "TELEGRAM_CHAT_ID_DEFINIDO: ${{ env.TELEGRAM_CHAT_ID != '' }}"

    - name: 5. Executar o Falcão da ODDS
      run: python main.py
      
    - name: 6. Salvar estado do bot (apostas, resultados, etc)
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'github-actions@github.com'
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Atualização automática do estado do bot"; git push)
