name: Rodar Falcão da ODDS

on:
  schedule:
    # --- NOVAS REGRAS DE AGENDAMENTO ---
    # Roda no minuto 0, a cada 2 horas, entre as 8h e as 22h
    - cron: '0 8-22/2 * * *'
    # Roda também à meia-noite (00:00)
    - cron: '0 0 * * *'
  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-falcao:
    runs-on: ubuntu-latest
    
    steps:
    - name: 1. Baixar o código
      uses: actions/checkout@v4

    - name: 2. Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 3. Instalar dependências
      run: pip install -r requirements.txt

    - name: 4. Executar o Falcão da ODDS
      env:
        API_KEY_ODDS: ${{ secrets.API_KEY_ODDS }} 
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
      
    - name: 5. Salvar estado do bot (apostas, resultados, etc)
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'github-actions@github.com'
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Atualização automática do estado do bot"; git push)
