name: Execução do Bot Falcão das Odds

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Roda a cada 2 horas (nos minutos 0, 2, 4, 6... horas UTC)
    - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Baixar o código
        uses: actions/checkout@v3

      - name: 2. Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: 3. Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: 4. Executar o Falcão das ODDS
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          API_KEY_ODDS: ${{ secrets.API_KEY_ODDS }}
          API_KEY_FOOTBALL: ${{ secrets.API_KEY_FOOTBALL }}
        run: python main.py
