# .github/workflows/rodar-analise.yml

name: Análise de Jogos do Falcão

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11-23 * * *'
    - cron: '0 0-3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixando o código do repositório
        uses: actions/checkout@v4

      # ### PASSO NOVO ###
      # Garante que começamos do zero, se necessário.
      - name: Limpar Cache Antigo (para depuração)
        run: rm -rf cache

      - name: Configurando o ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalando as dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executando o Robô Falcão
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_ODDS: ${{ secrets.API_KEY_ODDS }}
          API_KEY_RUNDOWN: ${{ secrets.API_KEY_RUNDOWN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
