steps:
    - uses: actions/checkout@v4
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Instalar dependências
      run: pip install -r requirements.txt
      
    # --- PASSO DE DETETIVE ADICIONADO AQUI ---
    - name: Verificar se os Segredos foram Carregados
      run: |
        echo "API_KEY_ODDS_DEFINIDO: ${{ env.API_KEY_ODDS != '' }}"
        echo "TELEGRAM_TOKEN_DEFINIDO: ${{ env.TELEGRAM_TOKEN != '' }}"
        echo "TELEGRAM_CHAT_ID_DEFINIDO: ${{ env.TELEGRAM_CHAT_ID != '' }}"

    - name: Executar o Falcão da ODDS
      env:
        API_KEY_ODDS: ${{ secrets.API_KEY }} 
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
      
    - name: Salvar estado do bot (apostas, resultados, etc)
      # ... (resto do arquivo)
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'github-actions@github.com'
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Atualização automática do estado do bot"; git push)
