name: Rodar Falcão da ODDS

on:
  schedule:
    # Roda a cada 4 horas
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-falcao:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Instalar dependências
      run: pip install -r requirements.txt
    - name: Executar o Falcão da ODDS
      env:
        # --- LINHA CORRIGIDA ABAIXO ---
        API_KEY_ODDS: ${{ secrets.API_KEY }} 
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
    - name: Salvar estado do bot (apostas, resultados, etc)
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'github-actions@github.com'
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Atualização automática do estado do bot"; git push)
