# .github/workflows/rodar-analise.yml (Versão com Cache Persistente)

name: Análise de Jogos do Falcão

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11-23 * * *'
    - cron: '0 0-3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixando o código do repositório
        uses: actions/checkout@v4

      # --- ETAPA DE CACHE (A MUDANÇA PRINCIPAL) ---
      # 1. Tenta restaurar a pasta de cache da execução anterior
      - name: Restaurando Cache
        uses: actions/cache@v3
        with:
          path: . # O diretório a ser salvo/restaurado (a pasta principal)
          # A chave de cache é baseada no dia. Um novo cache será criado a cada dia.
          key: bot-cache-${{ github.run_id }}
          restore-keys: |
            bot-cache-

      - name: Configurando o ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalando as dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executando o Robô Falcão
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_ODDS: ${{ secrets.API_KEY_ODDS }}
          API_KEY_RUNDOWN: ${{ secrets.API_KEY_RUNDOWN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
