name: Rodar Bot de Trade Esportivo

on:
  schedule:
    # Roda às 11h, 15h e 21h UTC (corresponde a 08h, 12h e 18h no seu fuso)
    - cron: '0 11,15,21 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Baixar o código
      uses: actions/checkout@v4
    - name: 2. Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: 3. Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 4. Executar o bot principal
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
    - name: 5. Salvar alterações (Commit & Push)
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add --all # Adiciona todos os arquivos novos ou modificados
        git diff --quiet && git diff --staged --quiet || (git commit -m "Atualização automática de arquivos de log"; git push)
